FROM denoland/deno:2.5.0

ARG CAPROVER_GIT_COMMIT_SHA=${CAPROVER_GIT_COMMIT_SHA}
ENV DENO_DEPLOYMENT_ID=${CAPROVER_GIT_COMMIT_SHA}

ARG IMAGOR_SECRET=${IMAGOR_SECRET}
ENV IMAGOR_SECRET=${IMAGOR_SECRET}
ARG IMAGOR_URL=${IMAGOR_URL}
ENV IMAGOR_URL=${IMAGOR_URL}
ARG UMAMI_SCRIPT_URL=${UMAMI_SCRIPT_URL}
ENV UMAMI_SCRIPT_URL=${UMAMI_SCRIPT_URL}
ARG UMAMI_WEBSITE_ID=${UMAMI_WEBSITE_ID}
ENV UMAMI_WEBSITE_ID=${UMAMI_WEBSITE_ID}

WORKDIR /app

COPY . .
RUN deno cache --allow-scripts main.ts
RUN deno task build

EXPOSE 8000

CMD ["run", "-A", "main.ts"]
