// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_index_index from "./routes/(index)/index.tsx";
import * as $_markdown_slug_ from "./routes/(markdown)/[slug].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
	routes: {
		"./routes/(index)/index.tsx": $_index_index,
		"./routes/(markdown)/[slug].tsx": $_markdown_slug_,
		"./routes/_404.tsx": $_404,
		"./routes/_app.tsx": $_app,
		"./routes/_layout.tsx": $_layout,
	},
	islands: {},
	baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
