// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $blog_slug_ from "./routes/blog/[slug].tsx";
import * as $blog_index from "./routes/blog/index.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $index from "./routes/index.tsx";
import * as $photos_album_photo_ from "./routes/photos/[album]/[photo].tsx";
import * as $photos_album_index from "./routes/photos/[album]/index.tsx";
import * as $photos_index from "./routes/photos/index.tsx";
import * as $projects from "./routes/projects.tsx";
import * as $work from "./routes/work.tsx";
import * as $PhotoKeyboardNavigation from "./islands/PhotoKeyboardNavigation.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
	routes: {
		"./routes/_404.tsx": $_404,
		"./routes/_app.tsx": $_app,
		"./routes/_layout.tsx": $_layout,
		"./routes/blog/[slug].tsx": $blog_slug_,
		"./routes/blog/index.tsx": $blog_index,
		"./routes/contact.tsx": $contact,
		"./routes/index.tsx": $index,
		"./routes/photos/[album]/[photo].tsx": $photos_album_photo_,
		"./routes/photos/[album]/index.tsx": $photos_album_index,
		"./routes/photos/index.tsx": $photos_index,
		"./routes/projects.tsx": $projects,
		"./routes/work.tsx": $work,
	},
	islands: {
		"./islands/PhotoKeyboardNavigation.tsx": $PhotoKeyboardNavigation,
	},
	baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
